# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode9.2
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet # We need cocoapods 1.1 which is still prerelease
- pod repo update
script:
- set -o pipefail
- xcodebuild test -workspace Example/WistiaKit.xcworkspace -scheme WistiaKit-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
